import { concept } from './model.mjs';

export const foundations = [
    concept('relational-model', 'foundations', 'Tables, rows & relations',
        'A table represents facts as rows with named, typed columns.',
        'When entities and relationships require consistent, queryable structure.',
        'Keys and constraints enforce relationships rather than relying on application convention.',
        'A shop stores a customer once and relates many orders to that customer.',
        `SELECT CustomerID, Name, City\nFROM dbo.Customers;`,
        'Tables have no guaranteed result order. Ordinary SQL also permits duplicate result rows.',
        'Does a table have guaranteed business ordering?', 'No. Use a final ORDER BY to guarantee result ordering.'),
    concept('sql-families', 'foundations', 'DDL, DML, DCL & TCL',
        'SQL statements define structures, query/change data, control access, or manage transactions.',
        'When choosing an operation for schema, rows, permissions, or transaction boundaries.',
        'Each operation has different permission, locking, and deployment consequences.',
        'A migration creates a table; an application inserts orders; an administrator grants access.',
        `CREATE TABLE dbo.Example (ID int PRIMARY KEY); -- DDL\nINSERT INTO dbo.Example (ID) VALUES (1);       -- DML\nSELECT ID FROM dbo.Example;                   -- query / DQL\nGRANT SELECT ON dbo.Example TO ReportingRole; -- DCL\nBEGIN TRANSACTION;                           -- TCL\nROLLBACK;`,
        'These are teaching categories. The GRANT example needs the principal ReportingRole to exist.',
        'Is CREATE a DML statement?', 'No. CREATE is DDL; INSERT, UPDATE, and DELETE change rows and are DML.'),
    concept('data-types', 'foundations', 'Choosing data types',
        'A type specifies the domain, representation, and operations of a value.',
        'When defining columns, routine parameters, and casts.',
        'Correct types reduce invalid values, rounding surprises, and implicit conversions.',
        'Prices use decimal, timestamps datetime2, and multilingual names nvarchar.',
        `CREATE TABLE dbo.TypeExample (\n    ID int NOT NULL,\n    Price decimal(12,2) NOT NULL,\n    CreatedAt datetime2(3) NOT NULL,\n    DisplayName nvarchar(100) NOT NULL,\n    IsActive bit NOT NULL\n);`,
        'float is approximate. Sizes, collations, precision, and scale change behavior and storage.',
        'Why use decimal rather than float for prices?', 'decimal has explicit decimal precision and scale; float may introduce binary approximation.'),
    concept('null', 'foundations', 'NULL & three-valued logic',
        'NULL marks missing or unknown information; a comparison can be TRUE, FALSE, or UNKNOWN.',
        'When absence has a defined business meaning.',
        'It explains filtering, aggregates, joins, and the NOT IN trap.',
        'An unknown email is different from a known empty email string.',
        `SELECT CustomerID, Name\nFROM dbo.Customers\nWHERE Email IS NULL;\n\nSELECT CustomerID, COALESCE(Email, N'Not supplied') AS Contact\nFROM dbo.Customers;`,
        'Email = NULL is not a NULL test. WHERE keeps only TRUE, not FALSE or UNKNOWN.',
        'What is NULL = NULL?', 'UNKNOWN under standard NULL semantics. Use IS NULL to test absence.'),
    concept('logical-order', 'foundations', 'Logical query processing',
        'Logical processing defines query meaning, not necessarily the physical execution order.',
        'When reasoning about aliases, aggregates, filters, and window results.',
        'It explains why SELECT aliases are normally unavailable in WHERE but usable in ORDER BY.',
        'Filter paid orders, group by customer, filter totals, then sort the result.',
        `SELECT CustomerID, SUM(Total) AS Spend\nFROM dbo.Orders\nWHERE Status = N'Paid'\nGROUP BY CustomerID\nHAVING SUM(Total) > 100\nORDER BY Spend DESC;`,
        'The optimizer can reorder compatible physical work without changing logical meaning.',
        'Can WHERE filter SUM(Total) at the same grouping level?', 'No. WHERE filters input rows; HAVING filters groups.',
        { diagram: 'flowchart TD\nSource["FROM / JOIN"] --> Filter["WHERE: input rows"]\nFilter --> Groups["GROUP BY"]\nGroups --> Having["HAVING: groups"]\nHaving --> Projection["SELECT and window expressions"]\nProjection --> Distinct["DISTINCT"]\nDistinct --> Sort["ORDER BY"]\nSort --> Limit["TOP / OFFSET-FETCH"]' }),
    concept('schema-database', 'foundations', 'Database vs schema vs table',
        'A database holds objects/data; a schema is a namespace and permission boundary inside it.',
        'When organizing domains and granting scoped access.',
        'Qualified names clarify ownership and dependencies.',
        'Sales.Orders and Audit.OrderEvents can live in the same database.',
        `CREATE SCHEMA Sales;\nGO\nCREATE TABLE Sales.ExampleOrder (OrderID int PRIMARY KEY);\nSELECT OrderID FROM Sales.ExampleOrder;`,
        'GO is a client-tool batch separator, not a T-SQL statement sent to the engine.',
        'Does dbo mean database?', 'No. dbo is a commonly used schema within a database.')
];