export const schema = [
    ['Customers', 'CustomerID (PK), Name, City, Email'],
    ['Orders', 'OrderID (PK), CustomerID (FK, nullable), OrderDate, Status, Total'],
    ['Products', 'ProductID (PK), Name, Category, Price'],
    ['OrderItems', '(OrderID, ProductID) (PK), Quantity, UnitPrice'],
    ['Employees', 'EmployeeID (PK), Name, ManagerID (self FK), Department, Salary']
];
export const seed = `PRAGMA foreign_keys = ON;
CREATE TABLE Customers(CustomerID INTEGER PRIMARY KEY, Name TEXT NOT NULL, City TEXT, Email TEXT);
CREATE TABLE Orders(OrderID INTEGER PRIMARY KEY, CustomerID INTEGER REFERENCES Customers(CustomerID), OrderDate TEXT NOT NULL, Status TEXT NOT NULL, Total NUMERIC NOT NULL CHECK(Total>=0));
CREATE TABLE Products(ProductID INTEGER PRIMARY KEY, Name TEXT NOT NULL, Category TEXT NOT NULL, Price NUMERIC NOT NULL CHECK(Price>=0));
CREATE TABLE OrderItems(OrderID INTEGER NOT NULL REFERENCES Orders(OrderID), ProductID INTEGER NOT NULL REFERENCES Products(ProductID), Quantity INTEGER NOT NULL CHECK(Quantity>0), UnitPrice NUMERIC NOT NULL, PRIMARY KEY(OrderID, ProductID));
CREATE TABLE Employees(EmployeeID INTEGER PRIMARY KEY, Name TEXT NOT NULL, ManagerID INTEGER REFERENCES Employees(EmployeeID), Department TEXT NOT NULL, Salary NUMERIC NOT NULL);
INSERT INTO Customers VALUES (1,'Asha','London','asha@example.test'),(2,'Ben','Paris','ben@example.test'),(3,'Chen','London',NULL),(4,'Diya','Berlin','diya@example.test'),(5,'Evan','Rome',NULL);
INSERT INTO Orders VALUES (101,1,'2026-01-02','Paid',40),(102,1,'2026-01-05','Paid',60),(103,2,'2026-01-05','Pending',20),(104,2,'2026-01-06','Paid',80),(105,3,'2026-01-07','Cancelled',30),(106,3,'2026-01-08','Paid',40),(107,NULL,'2026-01-09','Paid',15);
INSERT INTO Products VALUES (1,'Coffee','Drinks',4.5),(2,'Tea','Drinks',3),(3,'Sandwich','Food',8),(4,'Cake','Food',5),(5,'Mug','Goods',12);
INSERT INTO OrderItems VALUES (101,1,4,4.5),(101,2,2,3),(101,3,2,8),(102,5,5,12),(103,4,4,5),(104,3,10,8),(105,4,6,5),(106,3,5,8),(107,4,3,5);
INSERT INTO Employees VALUES (1,'Maya',NULL,'Executive',100000),(2,'Noah',1,'Sales',90000),(3,'Oliver',1,'Sales',90000),(4,'Priya',2,'Sales',70000),(5,'Remy',1,'Engineering',95000),(6,'Sofia',5,'Engineering',80000),(7,'Tara',5,'Engineering',80000);`;

export const labExamples = [
    { id: 'first-query', title: 'Your first query', concept: 'select', prompt: 'Return the five customer rows in stable key order.', sql: 'SELECT CustomerID, Name, City, Email\nFROM Customers ORDER BY CustomerID;', expected: [5] },
    { id: 'left-vs-inner', title: 'INNER vs LEFT results', concept: 'left-join', prompt: 'Compare six matched order rows with eight left-join rows, including Diya and Evan without orders.', sql: 'SELECT customer.Name, orders.OrderID\nFROM Customers AS customer\nINNER JOIN Orders AS orders ON orders.CustomerID = customer.CustomerID\nORDER BY customer.CustomerID, orders.OrderID;\n\nSELECT customer.Name, orders.OrderID\nFROM Customers AS customer\nLEFT JOIN Orders AS orders ON orders.CustomerID = customer.CustomerID\nORDER BY customer.CustomerID, orders.OrderID;', expected: [6, 8] },
    { id: 'left-filter', title: 'The misplaced WHERE filter', concept: 'outer-join-filter', prompt: 'The ON filter keeps every customer (six rows); the WHERE filter keeps only paid matches (four rows).', sql: "SELECT customer.Name, orders.OrderID\nFROM Customers AS customer LEFT JOIN Orders AS orders\nON orders.CustomerID=customer.CustomerID AND orders.Status='Paid'\nORDER BY customer.CustomerID, orders.OrderID;\n\nSELECT customer.Name, orders.OrderID\nFROM Customers AS customer LEFT JOIN Orders AS orders\nON orders.CustomerID=customer.CustomerID\nWHERE orders.Status='Paid'\nORDER BY customer.CustomerID, orders.OrderID;", expected: [6, 4] },
    { id: 'null-exclusion', title: 'NOT IN and the NULL trap', concept: 'not-exists', prompt: 'A NULL CustomerID exists on order 107. NOT IN returns zero rows; NOT EXISTS finds Diya and Evan.', sql: 'SELECT CustomerID, Name FROM Customers\nWHERE CustomerID NOT IN (SELECT CustomerID FROM Orders);\n\nSELECT customer.CustomerID, customer.Name FROM Customers AS customer\nWHERE NOT EXISTS (SELECT 1 FROM Orders AS orders WHERE orders.CustomerID=customer.CustomerID)\nORDER BY customer.CustomerID;', expected: [0, 2] },
    { id: 'count-null', title: 'Count rows vs supplied values', concept: 'aggregates', prompt: 'Five customers have three supplied emails; an unmatched LEFT JOIN row must not count as an order.', sql: 'SELECT COUNT(*) AS Customers, COUNT(Email) AS SuppliedEmails, COUNT(DISTINCT City) AS Cities FROM Customers;\n\nSELECT customer.Name, COUNT(*) AS JoinedRows, COUNT(orders.OrderID) AS Orders\nFROM Customers AS customer LEFT JOIN Orders AS orders ON orders.CustomerID=customer.CustomerID\nGROUP BY customer.CustomerID, customer.Name ORDER BY customer.CustomerID;', expected: [1, 5] },
    { id: 'salary-rank', title: 'Ranking ties side by side', concept: 'ranking', prompt: 'Noah and Oliver tie at 90,000. Compare unique positions, gapped ranks, and dense ranks.', sql: 'SELECT Name, Salary,\nROW_NUMBER() OVER (ORDER BY Salary DESC, EmployeeID) AS RowPosition,\nRANK() OVER (ORDER BY Salary DESC) AS SalaryRank,\nDENSE_RANK() OVER (ORDER BY Salary DESC) AS DenseSalaryRank\nFROM Employees ORDER BY Salary DESC, EmployeeID;', expected: [7] },
    { id: 'group-window', title: 'Grouping changes the grain', concept: 'window-functions', prompt: 'Grouping returns four customer groups including NULL; a window keeps all seven orders.', sql: 'SELECT CustomerID, SUM(Total) AS Spend FROM Orders GROUP BY CustomerID ORDER BY CustomerID;\n\nSELECT OrderID, CustomerID, Total, SUM(Total) OVER (PARTITION BY CustomerID) AS CustomerSpend\nFROM Orders ORDER BY OrderID;', expected: [4, 7] },
    { id: 'latest-order', title: 'Latest order per customer', concept: 'latest-row', prompt: 'Return orders 102, 104, and 106 for known customers.', sql: 'WITH Ranked AS (\nSELECT *, ROW_NUMBER() OVER (PARTITION BY CustomerID ORDER BY OrderDate DESC, OrderID DESC) AS Position\nFROM Orders WHERE CustomerID IS NOT NULL\n)\nSELECT OrderID, CustomerID, Total FROM Ranked WHERE Position=1 ORDER BY CustomerID;', expected: [3] },
    { id: 'running-total', title: 'Running customer spend', concept: 'window-frame', prompt: 'Asha progresses from 40 to 100. Use a unique order and an explicit ROWS frame.', sql: 'SELECT OrderID, CustomerID, Total,\nSUM(Total) OVER (PARTITION BY CustomerID ORDER BY OrderDate, OrderID\nROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS RunningSpend\nFROM Orders WHERE CustomerID IS NOT NULL ORDER BY CustomerID, OrderDate, OrderID;', expected: [6] },
    { id: 'double-count', title: 'Header totals after a line join', concept: 'grain-fanout', prompt: 'The true header total is 285. Summing headers after joining lines inflates it to 365.', sql: 'SELECT SUM(Total) AS CorrectHeaderTotal FROM Orders;\nSELECT SUM(orders.Total) AS InflatedHeaderTotal\nFROM Orders AS orders JOIN OrderItems AS lines ON lines.OrderID=orders.OrderID;\nSELECT SUM(Quantity * UnitPrice) AS CorrectLineTotal FROM OrderItems;', expected: [1, 1, 1] },
    { id: 'recursive', title: 'Employee hierarchy', concept: 'recursive-cte', prompt: 'Traverse the seeded hierarchy using SQLite WITH RECURSIVE. SQL Server uses WITH and can add MAXRECURSION.', sql: 'WITH RECURSIVE Org AS (\nSELECT EmployeeID, Name, ManagerID, 0 AS Depth FROM Employees WHERE ManagerID IS NULL\nUNION ALL\nSELECT employee.EmployeeID, employee.Name, employee.ManagerID, parent.Depth+1\nFROM Employees AS employee JOIN Org AS parent ON employee.ManagerID=parent.EmployeeID\n)\nSELECT * FROM Org ORDER BY Depth, EmployeeID;', expected: [7] },
    { id: 'rollback', title: 'A real local rollback', concept: 'acid', prompt: 'Observe an uncommitted price, roll it back, then verify the original value returns.', sql: 'BEGIN TRANSACTION;\nUPDATE Products SET Price=999 WHERE ProductID=1;\nSELECT Price AS TemporaryPrice FROM Products WHERE ProductID=1;\nROLLBACK;\nSELECT Price AS OriginalPrice FROM Products WHERE ProductID=1;', expected: [1, 1] }
];

export const schemaDiagram = 'erDiagram\nCUSTOMERS |o--o{ ORDERS : places\nORDERS ||--o{ ORDER_ITEMS : contains\nPRODUCTS ||--o{ ORDER_ITEMS : appears_in\nEMPLOYEES |o--o{ EMPLOYEES : manages';